### ISSUE TITLE
[Build] - Move from ant to gradle

### ISSUE THREAD

**Issue by anandbagmar** [anandbagmar/WAAT#2]
Ant is old. We want a better build tool integration. Lets move to gradle

**Comment by anandbagmar** [comment]
Added a gradle wrapper on top of ant. Now the same ant targets can be called from gradle. Next steps - start porting specific targets into gradle and eventually remove ant's build.xml

**Comment by sramalin** [comment]
To start with, Adding the dependancy management part to Gradle.

- Creating a dependency section in the gradle build file

- Adding all the jar references of required by the app and tests.

**Comment by sramalin** [comment]
Added a gradle task "copyDependenciesForAnt" which downloads the dependent jars to lib folder.

**Comment by anandbagmar** [comment]
done
