### ISSUE TITLE
Basic Query & suggestion

### ISSUE THREAD

**Issue by vikramvi** [anandbagmar/WAAT#29]
Is this project can be used for Web Site Analytics testing from real browser or only on Android platform ?

It's not very clear from README & also I was present during your talk in recent selenium conference, many felt it was too much details without actual code shown running like last talk about web page performance testing.

**Comment by anandbagmar** [comment]
Hi @vikramvi - WAAT can be used for Analytics automation via browser or Android / iOS platform. 

The talk in the recent Selenium Conference was NOT about WAAT. It was about Analytics testing in general - what is it, why is it important, and how can you test for the same. WAAT was a very small piece of that.

Let me know what help you need to set it up. Also, take a look at the tests in the repo, which shows exactly how you can use it.
